version: '3'
    
services:
  db:
    image: nouchka/sqlite3
  api:
    image: 00025/drfproducts:1.0.0
    command: python manage.py runserver 0.0.0.0:3000
    ports:
      - "3000:3000"
  web:
    image: 00025/perslacaffe:1.0.0
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - api

# Deploy final, presentado en clase. Pre correcciones y sugerencias